import Link from 'next/link'
import { notFound } from 'next/navigation'
import { HOTEL_BL_SITE_CONTROL_TYPES } from '@rnr/core'
import { db, getHotelBlDomainDetail } from '@rnr/data'
import { HhtSectionTabs } from '@/components/hht/HhtSectionTabs'
import { NULL_DISPLAY, num } from '@/lib/format'
import { updateHotelBlClassificationAction } from '../../actions'

export const dynamic = 'force-dynamic'

const label = (value: string | null | undefined): string => value?.replaceAll('_', ' ') ?? NULL_DISPLAY
const score = (value: number | null | undefined): string => value === null || value === undefined ? NULL_DISPLAY : value.toFixed(1)
const date = (value: Date | null | undefined): string => value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(value) : NULL_DISPLAY

export default async function DomainDetailPage({ params }: { params: Promise<{ domainId: string }> }) {
  const { domainId: rawId } = await params
  const domainId = Number(rawId)
  if (!Number.isInteger(domainId) || domainId <= 0) notFound()
  const detail = await getHotelBlDomainDetail(db(), domainId)
  if (!detail) notFound()
  const { domain, hotels, pages, contacts, opportunities, links } = detail
  return (
    <div className="opp-workspace hht-bl-workspace hotel-bl-workspace">
      <header className="run-page-head hht-bl-head"><div><Link href="/hotel-backlink-scout?view=domains" className="hotel-bl-back">← Domains</Link><h1 className="page-title">{domain.domain}</h1><p className="page-desc">{domain.entityName ?? label(domain.entityType)} · {num(domain.hotelCount)} associated hotel{domain.hotelCount === 1 ? '' : 's'}</p></div><a href={domain.canonicalUrl} target="_blank" rel="noreferrer" className="button-link">Open domain</a></header>
      <HhtSectionTabs active="hotel-backlink-scout" />
      <main className="hht-bl-view">
        <section className="hotel-bl-detail-grid">
          <section className="hotel-bl-detail-card"><h2>Domain evidence</h2><dl><Fact term="Root domain" value={domain.rootDomain} /><Fact term="Entity scope" value={domain.entityScope} /><Fact term="Entity type" value={domain.entityType} /><Fact term="Crawl status" value={domain.crawlStatus} /><Fact term="Last crawled" value={date(domain.lastCrawledAt)} /><Fact term="Press page" value={domain.hasPressPage ? 'Yes' : 'No'} /><Fact term="Awards page" value={domain.hasAwardsPage ? 'Yes' : 'No'} /><Fact term="Blog/news" value={domain.hasBlogOrNews ? 'Yes' : 'No'} /><Fact term="External editorial links" value={String(domain.externalPressLinkCount)} /><Fact term="Followed editorial links" value={String(domain.dofollowExternalPressLinkCount)} /><Fact term="Follow ratio" value={domain.pressLinkRatio === null ? null : `${Math.round(domain.pressLinkRatio * 100)}%`} /><Fact term="Latest press" value={date(domain.latestPressDate)} /><Fact term="Freshness confidence" value={domain.freshnessConfidence === null ? null : `${Math.round(domain.freshnessConfidence * 100)}%`} /></dl></section>
          <section className="hotel-bl-detail-card"><h2>Control &amp; SEO value</h2><dl><Fact term="Classification" value={domain.manualSiteControlType ?? domain.siteControlType} /><Fact term="Confidence" value={`${Math.round(domain.siteControlConfidence * 100)}%`} /><Fact term="Reason" value={domain.siteControlReason} /><Fact term="Authority score" value={domain.authorityScore?.toString()} /><Fact term="Organic traffic" value={domain.organicTraffic === null ? null : num(domain.organicTraffic)} /><Fact term="Referring domains" value={domain.referringDomains === null ? null : num(domain.referringDomains)} /><Fact term="Already links to HHT" value={domain.alreadyLinksToHht === null ? null : domain.alreadyLinksToHht ? 'Yes' : 'No'} /></dl><form action={updateHotelBlClassificationAction} className="hotel-bl-override-form"><input type="hidden" name="entity" value="domain" /><input type="hidden" name="id" value={domain.id} /><label><span>Manual override</span><select name="classification" defaultValue={domain.manualSiteControlType ?? domain.siteControlType}>{HOTEL_BL_SITE_CONTROL_TYPES.map((type) => <option key={type} value={type}>{label(type)}</option>)}</select></label><button type="submit">Save override</button></form></section>
        </section>

        <section className="hht-bl-section"><div className="hht-bl-section-head"><div><h2>Associated hotels</h2><p>One crawl can support many hotel-level opportunities.</p></div></div><div className="hht-bl-table-wrap"><table className="hht-bl-table"><thead><tr><th>Hotel</th><th>City</th><th>State</th><th>Role</th><th>Relationship</th><th>Validation</th><th className="num">Confidence</th></tr></thead><tbody>{hotels.map((hotel) => <tr key={`${hotel.hotelId}:${hotel.relationshipType}`}><td><Link href={`/hotel-backlink-scout/hotels/${hotel.hotelId}`}>{hotel.hotelName}</Link></td><td>{hotel.city ?? NULL_DISPLAY}</td><td>{hotel.state ?? NULL_DISPLAY}</td><td>{label(hotel.entityScope)} · {label(hotel.entityType)}</td><td>{label(hotel.manualRelationshipType ?? hotel.relationshipType)}</td><td title={hotel.urlValidationReason ?? undefined}>{label(hotel.urlValidationStatus)}</td><td className="num">{Math.round(hotel.confidence * 100)}%</td></tr>)}</tbody></table></div></section>

        <section className="hht-bl-section"><div className="hht-bl-section-head"><div><h2>Discovered editorial surfaces</h2><p>Stored crawl evidence and supported freshness dates.</p></div></div>{pages.length === 0 ? <div className="hht-bl-empty">No pages crawled.</div> : <div className="hht-bl-table-wrap"><table className="hht-bl-table"><thead><tr><th>Page</th><th>Type</th><th>Status</th><th className="num">External links</th><th className="num">Editorial</th><th className="num">Followed</th><th>Content date</th><th className="num">Date confidence</th></tr></thead><tbody>{pages.map((page) => <tr key={page.id}><td><a href={page.url} target="_blank" rel="noreferrer">{page.title ?? page.url}</a></td><td>{label(page.pageType)}</td><td>{page.statusCode ?? NULL_DISPLAY}</td><td className="num">{num(page.externalLinkCount)}</td><td className="num">{num(page.externalPressLinkCount)}</td><td className="num">{num(page.dofollowExternalPressLinkCount)}</td><td>{date(page.lastContentDate ?? page.lastModifiedOrDetectedDate)}</td><td className="num">{page.dateConfidence === null ? NULL_DISPLAY : `${Math.round(page.dateConfidence * 100)}%`}</td></tr>)}</tbody></table></div>}</section>

        <section className="hht-bl-section"><div className="hht-bl-section-head"><div><h2>External editorial links</h2><p>Normal links without nofollow, sponsored, or UGC are marked followed.</p></div></div>{links.length === 0 ? <div className="hht-bl-empty">No external editorial links found.</div> : <div className="hht-bl-table-wrap"><table className="hht-bl-table"><thead><tr><th>Destination</th><th>Publication</th><th>Anchor</th><th>rel</th><th>Follow</th><th>Nofollow</th><th>Sponsored</th><th>UGC</th></tr></thead><tbody>{links.map((link) => <tr key={link.id}><td><a href={link.destinationUrl} target="_blank" rel="noreferrer">{link.destinationDomain}</a></td><td>{link.publicationName ?? NULL_DISPLAY}</td><td>{link.anchorText ?? NULL_DISPLAY}</td><td className="mono">{link.rel ?? NULL_DISPLAY}</td><td><span className={`badge ${link.followed ? 'go' : 'neutral'}`}>{link.followed ? 'follow' : 'blocked'}</span></td><td>{link.nofollow ? 'yes' : 'no'}</td><td>{link.sponsored ? 'yes' : 'no'}</td><td>{link.ugc ? 'yes' : 'no'}</td></tr>)}</tbody></table></div>}</section>

        <section className="hotel-bl-detail-grid"><section className="hotel-bl-detail-card"><h2>Contacts</h2>{contacts.length === 0 ? <p className="muted">No public PR, media, marketing, or management contact found.</p> : <ul className="hotel-bl-evidence-list">{contacts.map((contact) => <li key={contact.id}><strong>{contact.name ?? contact.email ?? contact.phone ?? 'General contact'}</strong><span>{[contact.title, label(contact.contactType), contact.email, contact.phone].filter(Boolean).join(' · ')}</span><a href={contact.sourceUrl} target="_blank" rel="noreferrer">Evidence</a></li>)}</ul>}</section><section className="hotel-bl-detail-card"><h2>Opportunity scores</h2>{opportunities.length === 0 ? <p className="muted">No associated opportunities.</p> : <ul className="hotel-bl-evidence-list">{opportunities.map((opportunity) => <li key={opportunity.id}><Link href={`/hotel-backlink-scout/hotels/${opportunity.hotelId}`}><strong>{opportunity.hotelName}</strong></Link><span>{label(opportunity.relationshipType)} · feasibility {score(opportunity.feasibilityScore)} · value {score(opportunity.linkValueScore)} · fit {score(opportunity.contentFitScore)} · effort {score(opportunity.effortScore)} · priority {score(opportunity.priorityScore)} · {label(opportunity.status)}</span><details><summary>Score components</summary><pre>{JSON.stringify({ feasibility: opportunity.feasibilityComponents, linkValue: opportunity.linkValueComponents, contentFit: opportunity.contentFitComponents }, null, 2)}</pre></details></li>)}</ul>}</section></section>
      </main>
    </div>
  )
}

function Fact({ term, value }: { term: string; value: string | null | undefined }) { return <div><dt>{term}</dt><dd>{value || NULL_DISPLAY}</dd></div> }
