/**
 * The `save_lead` tool contract, and the parsing of what the model sends back.
 *
 * ==================== THE MODEL IS AN UNTRUSTED CALLER ====================
 * These arguments are generated by an LLM under time pressure from a phone call.
 * Booleans arrive as `true`, `"true"`, `"yes"`, `"Yes"`, `"unknown"`, `""`, and
 * absent. Numbers arrive as `"about 15 years"`. Zips arrive as `"53140-1234"`.
 *
 * Every coercion here fails to `null`, never to `false` and never to `0`. That is
 * the whole reason this file exists as a parsing layer rather than a cast:
 * `is_emergency: "unknown"` silently becoming `false` is the exact failure the
 * schema comment on that column warns about.
 * =========================================================================
 */

import { normalizeZip, toE164 } from './normalize.js'

/** Every field the agent can send. All optional -- it calls this mid-sentence. */
export interface SaveLeadArgs {
  name?: unknown
  phone?: unknown
  email?: unknown
  address_line?: unknown
  city?: unknown
  zip?: unknown
  problem?: unknown
  system_type?: unknown
  system_age_years?: unknown
  is_emergency?: unknown
  is_owner?: unknown
  is_commercial?: unknown
  appointment_at?: unknown
  hazard?: unknown
  notes?: unknown
}

/**
 * What the job is about.
 *
 * ==================== ONE COLUMN, A VOCABULARY PER TRADE ====================
 * `leads.system_type` is text, and the name is HVAC's. It stays that way -- renaming
 * a column to `job_type` buys a migration and changes nothing a reader could not get
 * from this comment.
 *
 * What DID have to change is the vocabulary. A plumbing line has no thermostats, and
 * putting "toilet" and "sewer backup" through an HVAC enum sent every plumbing call
 * to `other`: technically not wrong, and useless for deciding which lead to work
 * first or what a market's calls are actually about.
 *
 * The parser accepts the union, so a value is never rejected for belonging to
 * another trade. Only the tool schema handed to a given agent is narrowed, because
 * the enum is what the model is choosing from mid-call.
 * ==========================================================================
 */
export const HVAC_SYSTEM_TYPES = [
  'furnace',
  'air_conditioner',
  'heat_pump',
  'mini_split',
  'boiler',
  'water_heater',
  'thermostat',
  'other',
] as const

export const PLUMBING_JOB_TYPES = [
  'leak_burst_pipe',
  'drain_clog',
  'toilet',
  'sewer_backup',
  'water_heater',
  'faucet_fixture',
  'garbage_disposal',
  'water_pressure',
  'no_water',
  'install_replace',
  'repipe',
  'other',
] as const

export const SYSTEM_TYPES = [
  ...HVAC_SYSTEM_TYPES,
  ...PLUMBING_JOB_TYPES.filter(
    (t): t is Exclude<(typeof PLUMBING_JOB_TYPES)[number], 'water_heater' | 'other'> =>
      t !== 'water_heater' && t !== 'other',
  ),
] as const
export type SystemType = (typeof SYSTEM_TYPES)[number]

/** The enum a given trade's agent chooses from. Unknown niche -> HVAC. */
export function jobTypesForNiche(nicheSlug: string | null | undefined): readonly string[] {
  if (nicheSlug === 'plumber') return PLUMBING_JOB_TYPES
  return HVAC_SYSTEM_TYPES
}

/** The parsed, normalised result. Every field is explicitly nullable. */
export interface ParsedLead {
  name: string | null
  phone: string | null
  email: string | null
  addressLine: string | null
  city: string | null
  zip: string | null
  problem: string | null
  systemType: SystemType | null
  systemAgeYears: number | null
  isEmergency: boolean | null
  isOwner: boolean | null
  isCommercial: boolean | null
  appointmentAt: Date | null
  hazard: string | null
  notes: string | null
  /**
   * Which fields arrived with a usable value on THIS call of the tool.
   *
   * Distinct from the values themselves: "address is null" and "address was never
   * asked" are different bugs and only one of them is the agent's fault. Merged
   * cumulatively across calls by the ingest layer.
   */
  captured: string[]
}

// --- Coercions ---------------------------------------------------------------

function str(v: unknown, max = 500): string | null {
  if (typeof v !== 'string') return null
  const s = v.trim()
  if (s === '') return null
  // Models emit these as placeholders for "I don't know". Treated as absent.
  if (/^(unknown|n\/?a|none|null|undefined|tbd|not sure|not provided)$/i.test(s)) return null
  return s.slice(0, max)
}

const TRUTHY = new Set(['true', 'yes', 'y', '1', 'correct', 'affirmative', 'owner', 'commercial'])
const FALSY = new Set(['false', 'no', 'n', '0', 'incorrect', 'renter', 'residential', 'rent'])

/**
 * Tri-state boolean. Anything not clearly yes or no becomes null.
 *
 * "unknown", "maybe", "didn't ask", "" -> null. This is the single most important
 * coercion in the file: for `is_emergency`, a wrong `false` is a no-heat call in
 * January queued for Tuesday.
 */
export function triBool(v: unknown): boolean | null {
  if (typeof v === 'boolean') return v
  if (typeof v === 'number') return v === 1 ? true : v === 0 ? false : null
  if (typeof v !== 'string') return null
  const s = v.trim().toLowerCase()
  if (s === '') return null
  if (TRUTHY.has(s)) return true
  if (FALSY.has(s)) return false
  return null
}

/** "about 15 years" -> 15. Out-of-range or unparseable -> null. */
function years(v: unknown): number | null {
  if (typeof v === 'number') {
    return Number.isFinite(v) && v >= 0 && v <= 100 ? Math.round(v) : null
  }
  if (typeof v !== 'string') return null
  const m = /(\d{1,3})/.exec(v)
  if (!m) return null
  const n = Number(m[1])
  return n >= 0 && n <= 100 ? n : null
}

function systemType(v: unknown): SystemType | null {
  const s = str(v)
  if (!s) return null
  const t = s.toLowerCase().replace(/[^a-z]+/g, '_')
  if ((SYSTEM_TYPES as readonly string[]).includes(t)) return t as SystemType

  // The model does not reliably use the enum, so map the words it does use.

  /**
   * Water heater FIRST, and this order is load-bearing.
   *
   * The furnace pattern matches the substring "heater", so while it ran first every
   * "water heater" a caller described was filed as a furnace. Invisible on an HVAC
   * line (a water heater is a plausible furnace-adjacent job) and wrong on every
   * plumbing call, where water heaters are a large share of the work.
   */
  if (/water.?heater|hot.?water.?(tank|heater)|tankless/.test(s)) return 'water_heater'

  // --- Plumbing ---
  if (/sewer|main.?line|septic|sewage/.test(s)) return 'sewer_backup'
  if (/toilet|commode|w\.?c\b/.test(s)) return 'toilet'
  if (/disposal|disposer|insinkerator/.test(s)) return 'garbage_disposal'
  if (/clog|blocked|backed.?up|slow.?drain|\bdrain\b/.test(s)) return 'drain_clog'
  if (/burst|leak|pipe|flood/.test(s)) return 'leak_burst_pipe'
  if (/faucet|fixture|spigot|hose.?bib|shower.?valve|tap\b/.test(s)) return 'faucet_fixture'
  if (/repipe|re.?pipe|galvanized|polybutylene/.test(s)) return 'repipe'
  if (/pressure/.test(s)) return 'water_pressure'
  if (/no.?water/.test(s)) return 'no_water'
  if (/install|replace|replacement|new\s/.test(s)) return 'install_replace'

  // --- HVAC ---
  if (/mini.?split|ductless/.test(s)) return 'mini_split'
  if (/heat.?pump/.test(s)) return 'heat_pump'
  if (/furnace|heating/.test(s)) return 'furnace'
  if (/\bac\b|a\/c|air.?condition/.test(s)) return 'air_conditioner'
  if (/boiler|radiator/.test(s)) return 'boiler'
  if (/thermostat|nest|ecobee/.test(s)) return 'thermostat'
  if (/heater/.test(s)) return 'furnace'
  return 'other'
}

/** ISO-ish datetime. Rejects anything unparseable or absurdly far out. */
function when(v: unknown): Date | null {
  const s = str(v)
  if (!s) return null
  const d = new Date(s)
  if (Number.isNaN(d.getTime())) return null
  const now = Date.now()
  // A year out is not a booking, it is a hallucinated date.
  if (d.getTime() < now - 86_400_000 || d.getTime() > now + 365 * 86_400_000) return null
  return d
}

// --- Parse -------------------------------------------------------------------

/**
 * Field names the Retell builder may use instead of ours.
 *
 * ==================== WHY ALIASES, NOT A RENAME ====================
 * Whoever builds the conversation names the tool parameters, and their names are
 * often better than these: `caller_name` and `callback_number` say more than `name`
 * and `phone`. Demanding an exact match makes the integration brittle in the worst
 * possible way -- the endpoint returns `200 saved:true` and stores a lead with every
 * field null, because nothing threw and nothing was recognised.
 *
 * Caught live: a flow wired with exactly these five names would have produced empty
 * leads on every call, and the only visible symptom would have been a dashboard full
 * of rows with no data.
 *
 * Canonical name on the left, accepted synonyms on the right.
 * ==================================================================
 */
const FIELD_ALIASES: Record<string, readonly string[]> = {
  name: ['caller_name', 'customer_name', 'full_name', 'contact_name'],
  phone: ['callback_number', 'phone_number', 'caller_number', 'contact_number', 'callback'],
  email: ['email_address'],
  address_line: ['service_address', 'address', 'street_address', 'property_address'],
  city: ['service_city'],
  zip: ['zip_code', 'postal_code', 'zipcode'],
  problem: ['problem_description', 'issue', 'issue_description', 'reason_for_call'],
  system_type: ['equipment_type', 'system'],
  system_age_years: ['system_age', 'equipment_age', 'age_of_system'],
  is_emergency: ['emergency', 'is_urgent', 'urgent'],
  is_owner: ['homeowner_status', 'is_homeowner', 'owner_status', 'owns_home'],
  is_commercial: ['is_business', 'commercial'],
  appointment_at: ['appointment', 'appointment_time', 'scheduled_at'],
  hazard: ['safety_hazard', 'hazard_type'],
  notes: ['additional_notes', 'other_details'],
}

/**
 * Resolve a canonical field from the raw object, trying aliases in order.
 *
 * Case- and separator-insensitive: a builder may emit `CallerName` or `caller-name`.
 */
function readField(raw: Record<string, unknown>, canonical: string): unknown {
  const normalize = (k: string): string => k.toLowerCase().replace(/[^a-z0-9]/g, '')
  const wanted = [canonical, ...(FIELD_ALIASES[canonical] ?? [])].map(normalize)

  for (const [key, value] of Object.entries(raw)) {
    if (value === null || value === undefined || value === '') continue
    if (wanted.includes(normalize(key))) return value
  }
  return undefined
}

export function parseSaveLeadArgs(raw: unknown): ParsedLead {
  const bag = (typeof raw === 'object' && raw !== null ? raw : {}) as Record<string, unknown>
  const a = Object.fromEntries(
    Object.keys(FIELD_ALIASES).map((canonical) => [canonical, readField(bag, canonical)]),
  ) as SaveLeadArgs
  const captured: string[] = []
  const mark = <T>(field: string, value: T): T => {
    if (value !== null && value !== undefined) captured.push(field)
    return value
  }

  const addressLine = str(a.address_line, 200)

  /**
   * A single `service_address` usually carries the zip inside it.
   *
   * Without pulling it out, `in_service_area` stays null on every lead from a flow
   * that collects one address string -- and that column is what decides whether the
   * agent should have declined the job. Falling back to the address means the check
   * works for the common case instead of only the ideal one.
   */
  const zip = normalizeZip(str(a.zip)) ?? normalizeZip(addressLine)

  return {
    name: mark('name', str(a.name, 120)),
    phone: mark('phone', toE164(String(a.phone ?? ''))),
    email: mark('email', emailOf(a.email)),
    addressLine: mark('addressLine', addressLine),
    city: mark('city', str(a.city, 80)),
    zip: mark('zip', zip),
    problem: mark('problem', str(a.problem, 1000)),
    systemType: mark('systemType', systemType(a.system_type)),
    systemAgeYears: mark('systemAgeYears', years(a.system_age_years)),
    isEmergency: mark('isEmergency', triBool(a.is_emergency)),
    isOwner: mark('isOwner', triBool(a.is_owner)),
    isCommercial: mark('isCommercial', triBool(a.is_commercial)),
    appointmentAt: mark('appointmentAt', when(a.appointment_at)),
    hazard: mark('hazard', str(a.hazard, 200)),
    notes: mark('notes', str(a.notes, 2000)),
    captured,
  }
}

function emailOf(v: unknown): string | null {
  const s = str(v, 200)
  if (!s) return null
  // Agents transcribe "at" and "dot" literally. Repair before validating.
  const repaired = s
    .replace(/\s+at\s+/gi, '@')
    .replace(/\s+dot\s+/gi, '.')
    .replace(/\s+/g, '')
    .toLowerCase()
  return /^[^@\s]+@[^@\s]+\.[a-z]{2,}$/.test(repaired) ? repaired : null
}

// --- Qualification -----------------------------------------------------------

/** The fields a lead needs before anyone can act on it. */
export const REQUIRED_FOR_QUALIFIED = ['name', 'phone', 'problem'] as const

export interface QualificationInput {
  name: string | null
  phone: string | null
  problem: string | null
  inServiceArea: boolean | null
  isOwner: boolean | null
}

/**
 * Is this lead actionable?
 *
 * ==================== NULL IS A REAL ANSWER HERE ====================
 * Returns null when the call did not get far enough to tell -- which is not the
 * same as "not qualified". `leads.qualified` is nullable and sorts LAST in the
 * UI, exactly like `scan_targets.difficulty`: a `false` would read as "we looked
 * at this and rejected it", when in fact nobody has looked.
 * ====================================================================
 */
export function qualifyLead(input: QualificationInput): boolean | null {
  const hasContact = input.name !== null && input.phone !== null
  // Nothing at all captured: the call did not reach qualification.
  if (!hasContact && input.problem === null) return null

  // A phone number is the floor. Without it nobody can be called back, so this
  // is a definite no rather than an unknown.
  if (input.phone === null) return false

  // Explicitly outside the area is a definite no for booking, though the lead is
  // still stored and still resellable.
  if (input.inServiceArea === false) return false

  // A renter cannot authorise work. Known-renter is a no; unknown is not.
  if (input.isOwner === false) return false

  if (input.name === null || input.problem === null) return null
  return true
}

// --- The schema to register with Retell --------------------------------------

/**
 * JSON Schema for the `save_lead` custom function.
 *
 * Emitted by `pnpm voice:agent-config` so the Retell side is generated from this
 * file rather than typed into a dashboard twice.
 */
export function buildSaveLeadSchema(nicheSlug?: string | null): Record<string, unknown> {
  const plumbing = nicheSlug === 'plumber'
  return {
    ...SAVE_LEAD_SCHEMA,
    properties: {
      ...SAVE_LEAD_SCHEMA.properties,
      system_type: {
        type: 'string',
        enum: [...jobTypesForNiche(nicheSlug)],
        description: 'What the job is about. Omit if never established.',
      },
      is_emergency: {
        type: 'boolean',
        description: plumbing
          ? 'True only if you established urgency: active flooding, a burst pipe, a major ' +
            'uncontrolled leak, sewage backing up, no working toilet, or a safety hazard. ' +
            'OMIT this field entirely if you did not ask -- do not guess false.'
          : SAVE_LEAD_SCHEMA.properties.is_emergency.description,
      },
      hazard: {
        type: 'string',
        description: plumbing
          ? 'If a safety hazard was reported, name it: gas, water_electrical, sewage.'
          : SAVE_LEAD_SCHEMA.properties.hazard.description,
      },
    },
  }
}

/** The HVAC schema, and the shape every niche's schema is derived from. */
export const SAVE_LEAD_SCHEMA = {
  type: 'object',
  properties: {
    name: { type: 'string', description: "The caller's full name." },
    phone: { type: 'string', description: 'Callback number, digits only or E.164.' },
    email: { type: 'string', description: 'Email if offered. Do not ask for it twice.' },
    address_line: { type: 'string', description: 'Street address of the service location.' },
    city: { type: 'string' },
    zip: { type: 'string', description: '5-digit ZIP of the service location.' },
    problem: { type: 'string', description: "The problem in the caller's own words." },
    system_type: { type: 'string', enum: [...HVAC_SYSTEM_TYPES] },
    system_age_years: { type: 'number', description: 'Approximate age. Omit if unknown.' },
    is_emergency: {
      type: 'boolean',
      description:
        'True only if you established urgency: no heat in cold, no cooling in heat, water, ' +
        'or a safety hazard. OMIT this field entirely if you did not ask -- do not guess false.',
    },
    is_owner: {
      type: 'boolean',
      description: 'True if they own the property. OMIT if not established.',
    },
    is_commercial: { type: 'boolean', description: 'True for a business. OMIT if not established.' },
    appointment_at: { type: 'string', description: 'ISO 8601 datetime if a time was agreed.' },
    hazard: {
      type: 'string',
      description: 'If a safety hazard was reported, name it: gas, carbon_monoxide, fire_electrical.',
    },
    notes: { type: 'string', description: 'Anything else useful to the technician.' },
  },
  required: [],
} as const

export const SAVE_LEAD_DESCRIPTION =
  'Save or update the caller as a lead. Call this as soon as you have a name and phone number, ' +
  'then again whenever you learn something new. Do not wait until the end of the call. ' +
  'Do not tell the caller you are saving anything.'
